### ISSUE TITLE
When using tailwind-config option, accept paths based on root of importer

### ISSUE THREAD

**Issue by georgesboris** [matheus23/elm-tailwind-modules#1]
**Goal**

Say a have a project with the structure like this:

```
/my-project
  package.json
  tailwind.config.js
```

I would like to be able to call:

```
elm-tailwind-modules --tailwind-config ./tailwind.config.js
```

**Problem**

Currently, I need to specify to full relative path based on the internal structure of the publish elm-tailwind-modules package:

```
elm-tailwind-modules --tailwind-config ../../../tailwind.config.js
```

This is not as intuitive and may lead to problems – e.g. if you change your internal folder structure, this relative path would not work anymore.

**Nice to have**

It would be even better if elm-tailwind-modules automatically detected if I had a `tailwind.config.js` at the root of my project folder (as this is the default) and if I wanted to specify a different one, I would pass in this extra option (maintaining the same path behavior previously described).

I'm more than happy to help out with a PR here! 🙂 If this is desirable, just let me know!
Cheers and props for the great work!

**Comment by matheus23** [comment]
> Currently, I need to specify to full relative path based on the internal structure of the publish elm-tailwind-modules package:
>
>     elm-tailwind-modules --tailwind-config ../../../tailwind.config.js
>
> This is not as intuitive and may lead to problems – e.g. if you change your internal folder structure, this relative path would not work anymore.

This sounds like a bug to me.

What's the directory you run `elm-tailwind-modules` from?

Did you figure out why you need to go back exactly 3 levels?

I feel like I don't 100% understand what's going on here.

---

I think the path should be relative to where you run the CLI from. If that's not the case, this is a bug.

> I'm more than happy to help out with a PR here! :slightly_smiling_face: If this is desirable, just let me know!

Awesome! If you want to take a look and it ends up (as I'm expecting at the moment) just some small changes, please open a PR and I'll merge it.

> It would be even better if elm-tailwind-modules automatically detected if I had a tailwind.config.js at the root of my project folder (as this is the default) and if I wanted to specify a different one, I would pass in this extra option (maintaining the same path behavior previously described).

Although this makes sense, it can be a little confusing to the user. Not specifying a tailwind config could also mean that the CLI will use a default one. I imagine there's some case in which the user doesn't specify a tailwind config and expects the CLI to use the one at the project root, but it ends up using a default config.
So I think we should either have a default config feature or a default config path feature.

>  Cheers and props for the great work!

Thank you! :heart:

**Comment by georgesboris** [comment]
I'm using `elm-tailwind-modules` through an npm script. When running it without all the relative path stuff it results in this error:

```bash
Error: Cannot find module './tailwind.config.js'
Require stack:
- /###/node_modules/elm-tailwind-modules/dist/cli.js
```

So I need to require it in relation to `node_modules/elm-tailwind-modules/dist` .
BTW I'm running on a macOS Big Sur (but I don't think that matters that much… is just usual node stuff)

I can take a look at it this weekend! 🙂 I will open a PR if I find anything.
