### ISSUE TITLE
Tailwindcss 3.3.0 breaks generated elm code (through from|to|via utilities)

### ISSUE THREAD

**Issue by nidico** [matheus23/elm-tailwind-modules#25]
Tailwind 3.3.0 [introduced new `from-x%`|`to-x%`|`via-x%` utility classes](https://github.com/tailwindlabs/tailwindcss/pull/10886) which break the generated elm code in both elm-tailwind-modules 0.4.1 and 0.5.0-alpha5.

The invalid generated elm code looks like this:

```elm
from_0% : Css.Style
from_0% =
    Css.property "--tw-gradient-from-position" "0%"
```

Unfortunately, `package.json` currently allows updates to `^3.1.6` (semver compatible to 3.1.6) which includes 3.3.x, so (as long as this isn't properly fixed) intermediate releases with pinned tailwindcss < 3.3 could be a quick fix. Otherwise users of the library can just locally pin tailwindcss to e.g. `3.2.7`.

**Comment by matheus23** [comment]
Good catch.
This needs to be fixed here:
https://github.com/matheus23/elm-tailwind-modules/blob/f3bb237baafa52b1252f819b65409df436ad6680/src/helpers.ts#L24-L50
