### ISSUE TITLE
Tailwind plugin not being generated

### ISSUE THREAD

**Issue by darrow97** [matheus23/elm-tailwind-modules#29]
Here is a minimal example public repository that reproduces the situation I am encountering: [elm-tailwind-with-daisyui](https://github.com/xeticode/elm-tailwind-with-daisy-ui).  

Here is the link to the DaisyUI site: https://daisyui.com/

In the tailwind config file, you will see a color value named `i_am_blue`. This is used as a way to verify the generated elm files used the custom tailwind config file.

Steps to reproduce :
1. From project root, run `npx elm-tailwind-modules --tailwind-config ./tailwind.config.js`

Expected outcome:
1. Something indicating the plugin was generated in the resulting elm code (I searched for various DaisyUI component names in `Theme.elm` and `Utilities.elm`

Actual outcome:
1. No DaisyUI code is reproduced in the generated elm code

**Comment by matheus23** [comment]
Thank you for that repository, that helps with troubleshooting *a ton*.

I found out the issue: You're accidentally disabling the daisyui plugin with this line:

https://github.com/xeticode/elm-tailwind-with-daisy-ui/blob/62b0d6ee3f827621ab25fcb0e29dc52e4e59bbdb/tailwind.config.js#L12

Delete that line, and it should work :)

**Comment by matheus23** [comment]
I was in contact with the author in another way, and removing that line seems to have fixed the issue :)
