### ISSUE TITLE
Tailwind 2.0 2xl breakpoint causes invalid Elm code

### ISSUE THREAD

**Issue by mcasper** [matheus23/elm-tailwind-modules#3]
Hey folks, thank you for this wonderful tool!

It looks like the (relatively) new 2xl breakpoint introduced in Tailwind 2.0 causes this library to generate invalid Elm functions:
https://blog.tailwindcss.com/tailwindcss-v2#extra-wide-2-xl-breakpoint
```
Compiling ...-- WEIRD DECLARATION -------------------------------- src/Tailwind/Utilities.elm

I am trying to parse a declaration, but I am getting stuck here:

11196| 2xl__absolute : Css.Style
```

This is easy to work around by disabling the breakpoint in your tailwind config, but just wanted to report it in case it wasn't known.

**Comment by matheus23** [comment]
Hi mcasper, thanks for the kind word.

Yes, we should fix this.

Just wanted to let you (or anyone reading this) know you should not have to disable the breakpoint, but instead disable variants in your tailwind config, via setting this in your tailwind configuration: `variant: []`.
